"""empty message

Revision ID: 07942dedce4d
Revises: 56f6b1f51d20
Create Date: 2021-10-16 00:26:51.208965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07942dedce4d'
down_revision = '56f6b1f51d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarifas', sa.Column('id_transport', sa.Integer(), nullable=True))
    op.drop_constraint('tarifas_transportista_fkey', 'tarifas', type_='foreignkey')
    op.create_foreign_key(None, 'tarifas', 'transportista', ['id_transport'], ['id_transport'])
    op.drop_column('tarifas', 'transportista')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarifas', sa.Column('transportista', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tarifas', type_='foreignkey')
    op.create_foreign_key('tarifas_transportista_fkey', 'tarifas', 'transportista', ['transportista'], ['id_transport'])
    op.drop_column('tarifas', 'id_transport')
    # ### end Alembic commands ###
