"""empty message

<<<<<<< HEAD:migrations/versions/af99d9491fbc_.py
Revision ID: af99d9491fbc
Revises: 
Create Date: 2021-10-24 23:55:58.033257
=======
Revision ID: 3df958031ff1
Revises: 
Create Date: 2021-10-24 06:27:23.297121
>>>>>>> 605255972310652012128fe132b3cc4944edb015:migrations/versions/3df958031ff1_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/af99d9491fbc_.py
revision = 'af99d9491fbc'
=======
revision = '3df958031ff1'
>>>>>>> 605255972310652012128fe132b3cc4944edb015:migrations/versions/3df958031ff1_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transportista',
    sa.Column('id_transport', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('rut', sa.String(length=50), nullable=False),
    sa.Column('transAddress', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_transport'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('vendedor',
    sa.Column('id_vendor', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('rut', sa.String(length=50), nullable=False),
    sa.Column('initialAddress', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_vendor'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('initialAddress'),
    sa.UniqueConstraint('lastName'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('encomiendas',
    sa.Column('id_package', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('originAddress', sa.String(length=50), nullable=True),
    sa.Column('destinationAddress', sa.String(length=50), nullable=True),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.Column('zoneDestino', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.String(length=50), nullable=True),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('mensaje', sa.String(length=1000), nullable=True),
    sa.Column('id_transport', sa.Integer(), nullable=True),
    sa.Column('name_transport', sa.String(length=50), nullable=True),
    sa.Column('phone_transport', sa.Integer(), nullable=True),
    sa.Column('id_seller', sa.Integer(), nullable=True),
    sa.Column('name_seller', sa.String(length=50), nullable=True),
    sa.Column('phone_seller', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_seller'], ['vendedor.id_vendor'], ),
    sa.ForeignKeyConstraint(['id_transport'], ['transportista.id_transport'], ),
    sa.PrimaryKeyConstraint('id_package'),
    sa.UniqueConstraint('id_package')
    )
    op.create_table('tarifas',
    sa.Column('id_fee', sa.Integer(), nullable=False),
    sa.Column('id_transport', sa.Integer(), nullable=True),
    sa.Column('name_transport', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('zoneDestino', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_transport'], ['transportista.id_transport'], ),
    sa.PrimaryKeyConstraint('id_fee')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarifas')
    op.drop_table('encomiendas')
    op.drop_table('vendedor')
    op.drop_table('transportista')
    # ### end Alembic commands ###
