"""empty message

Revision ID: 56f6b1f51d20
Revises: 9ed3fc142d4d
Create Date: 2021-10-15 23:32:26.381564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f6b1f51d20'
down_revision = '9ed3fc142d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'encomiendas', ['id_package'])
    op.add_column('tarifas', sa.Column('transportista', sa.Integer(), nullable=True))
    op.drop_constraint('tarifas_id_transport_fkey', 'tarifas', type_='foreignkey')
    op.create_foreign_key(None, 'tarifas', 'transportista', ['transportista'], ['id_transport'])
    op.drop_column('tarifas', 'id_transport')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarifas', sa.Column('id_transport', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tarifas', type_='foreignkey')
    op.create_foreign_key('tarifas_id_transport_fkey', 'tarifas', 'transportista', ['id_transport'], ['id_transport'])
    op.drop_column('tarifas', 'transportista')
    op.drop_constraint(None, 'encomiendas', type_='unique')
    # ### end Alembic commands ###
