"""empty message

Revision ID: 5b2dec595139
Revises: 7f6d1a7a1aed
Create Date: 2021-10-01 15:04:34.262484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2dec595139'
down_revision = '7f6d1a7a1aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('encomiendas_status_key', 'encomiendas', type_='unique')
    op.drop_constraint('encomiendas_zone_key', 'encomiendas', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('encomiendas_zone_key', 'encomiendas', ['zone'])
    op.create_unique_constraint('encomiendas_status_key', 'encomiendas', ['status'])
    # ### end Alembic commands ###
