"""empty message

Revision ID: 749d747b645f
Revises: f258a4d06640
Create Date: 2021-10-18 03:40:42.430523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749d747b645f'
down_revision = 'f258a4d06640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('encomiendas', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('encomiendas', 'zone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('encomiendas', 'zoneDestino',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('encomiendas', 'weight',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('encomiendas', 'dimensions',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('encomiendas', 'price',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('encomiendas', 'mensaje',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('encomiendas', 'name_transport',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('encomiendas', 'phone_transport',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('encomiendas', 'name_seller',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('encomiendas', 'phone_seller',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('encomiendas', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('encomiendas_phone_seller_key', 'encomiendas', type_='unique')
    op.drop_constraint('encomiendas_phone_transport_key', 'encomiendas', type_='unique')
    op.drop_constraint('encomiendas_rating_key', 'encomiendas', type_='unique')
    op.create_unique_constraint(None, 'encomiendas', ['destinationAddress'])
    op.create_unique_constraint(None, 'encomiendas', ['originAddress'])
    op.create_unique_constraint(None, 'encomiendas', ['id_package'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'encomiendas', type_='unique')
    op.drop_constraint(None, 'encomiendas', type_='unique')
    op.drop_constraint(None, 'encomiendas', type_='unique')
    op.create_unique_constraint('encomiendas_rating_key', 'encomiendas', ['rating'])
    op.create_unique_constraint('encomiendas_phone_transport_key', 'encomiendas', ['phone_transport'])
    op.create_unique_constraint('encomiendas_phone_seller_key', 'encomiendas', ['phone_seller'])
    op.alter_column('encomiendas', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('encomiendas', 'phone_seller',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('encomiendas', 'name_seller',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('encomiendas', 'phone_transport',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('encomiendas', 'name_transport',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('encomiendas', 'mensaje',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('encomiendas', 'price',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('encomiendas', 'dimensions',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('encomiendas', 'weight',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('encomiendas', 'zoneDestino',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('encomiendas', 'zone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('encomiendas', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
