"""empty message

Revision ID: 7f6d1a7a1aed
Revises: 40e16d5824a9
Create Date: 2021-10-01 14:40:33.986284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6d1a7a1aed'
down_revision = '40e16d5824a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encomiendas', sa.Column('lat', sa.Integer(), nullable=True))
    op.add_column('encomiendas', sa.Column('lng', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'encomiendas', ['lng'])
    op.create_unique_constraint(None, 'encomiendas', ['lat'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'encomiendas', type_='unique')
    op.drop_constraint(None, 'encomiendas', type_='unique')
    op.drop_column('encomiendas', 'lng')
    op.drop_column('encomiendas', 'lat')
    # ### end Alembic commands ###
