"""empty message

Revision ID: afe44a4670bc
Revises: 0af008e9457d
Create Date: 2021-10-04 01:04:09.812638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe44a4670bc'
down_revision = '0af008e9457d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'encomiendas', ['id_package'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'encomiendas', type_='unique')
    # ### end Alembic commands ###
