"""empty message

Revision ID: f258a4d06640
Revises: 
Create Date: 2021-10-18 02:42:02.211562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f258a4d06640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transportista',
    sa.Column('id_transport', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('rut', sa.String(length=50), nullable=False),
    sa.Column('transAddress', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_transport'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('vendedor',
    sa.Column('id_vendor', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('rut', sa.String(length=50), nullable=False),
    sa.Column('initialAddress', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_vendor'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('initialAddress'),
    sa.UniqueConstraint('lastName'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('encomiendas',
    sa.Column('id_package', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('originAddress', sa.String(length=50), nullable=True),
    sa.Column('destinationAddress', sa.String(length=50), nullable=True),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('zoneDestino', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.String(length=50), nullable=False),
    sa.Column('dimensions', sa.String(length=50), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.String(length=1000), nullable=False),
    sa.Column('id_transport', sa.Integer(), nullable=True),
    sa.Column('name_transport', sa.String(length=50), nullable=False),
    sa.Column('phone_transport', sa.Integer(), nullable=False),
    sa.Column('id_seller', sa.Integer(), nullable=True),
    sa.Column('name_seller', sa.String(length=50), nullable=False),
    sa.Column('phone_seller', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_seller'], ['vendedor.id_vendor'], ),
    sa.ForeignKeyConstraint(['id_transport'], ['transportista.id_transport'], ),
    sa.PrimaryKeyConstraint('id_package'),
    sa.UniqueConstraint('id_package'),
    sa.UniqueConstraint('phone_seller'),
    sa.UniqueConstraint('phone_transport'),
    sa.UniqueConstraint('rating')
    )
    op.create_table('tarifas',
    sa.Column('id_fee', sa.Integer(), nullable=False),
    sa.Column('id_transport', sa.Integer(), nullable=True),
    sa.Column('name_transport', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('zoneDestino', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_transport'], ['transportista.id_transport'], ),
    sa.PrimaryKeyConstraint('id_fee')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarifas')
    op.drop_table('encomiendas')
    op.drop_table('vendedor')
    op.drop_table('transportista')
    # ### end Alembic commands ###
