"""empty message

Revision ID: f7818fb05f53
Revises: 89bc81b66344
Create Date: 2021-10-09 02:58:06.908286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7818fb05f53'
down_revision = '89bc81b66344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'encomiendas', ['id_package'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'encomiendas', type_='unique')
    # ### end Alembic commands ###
