"""empty message

Revision ID: ffb6765f7f37
Revises: 
Create Date: 2021-10-09 13:33:07.590910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb6765f7f37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transportista',
    sa.Column('id_transport', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('rut', sa.String(length=50), nullable=False),
    sa.Column('transAddress', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_transport'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('vendedor',
    sa.Column('id_vendor', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('rut', sa.String(length=50), nullable=False),
    sa.Column('initialAddress', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_vendor'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('initialAddress'),
    sa.UniqueConstraint('lastName'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('direcciones',
    sa.Column('id_direccion', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=50), nullable=False),
    sa.Column('pertenece', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pertenece'], ['vendedor.id_vendor'], ),
    sa.PrimaryKeyConstraint('id_direccion')
    )
    op.create_table('tarifas',
    sa.Column('id_fee', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.Column('transport', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('zoneDestino', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['transport'], ['transportista.id_transport'], ),
    sa.PrimaryKeyConstraint('id_fee')
    )
    op.create_table('encomiendas',
    sa.Column('id_package', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('destinationAddress', sa.String(length=50), nullable=True),
    sa.Column('originAddress', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('transport', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['originAddress'], ['direcciones.id_direccion'], ),
    sa.ForeignKeyConstraint(['transport'], ['transportista.id_transport'], ),
    sa.PrimaryKeyConstraint('id_package'),
    sa.UniqueConstraint('id_package')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encomiendas')
    op.drop_table('tarifas')
    op.drop_table('direcciones')
    op.drop_table('vendedor')
    op.drop_table('transportista')
    # ### end Alembic commands ###
